	
	<script src="<?php echo Mage::getDesign()->getSkinUrl()?>bargainprice/js/jquery-1.8.0.min.js" type="text/javascript"></script>

	<script type="text/javascript"> 
		function getBaseUrl() { return '<?php  echo Mage::getBaseUrl() ?>'; } 
		function getMediaUrl() { return '<?php  echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>'; } 

	</script>
	
<div id="bargainprice_form" class="fieldset ">
    <div class="hor-scroll">
	<p class="info-cancelform-top">Fill the information to send customer.</p>
<?php $req_id = $this->getRequest()->getParam('id'); 
      $req_url = $this->getUrl('*/*/cancelform/id/'.$req_id).'?isAjax=true';
?>
<form>
     <table cellspacing="0" class="form-list">
      <tbody>

        <tr>
        <td class="label"><label for="minimum_price">Your Final Minimum  Price <span class="required">*</span></label></td>
    	<td class="value"><input type="text" class="required-entry input-text required-entry" value="" name="minimum_price" id="minimum_price"></td>
    	</tr>

	<tr>
        <td class="label"><label for="message">Message <span class="required">*</span></label></td>
	<td class="value"><textarea style = "max-height:170px;max-width:275px;"rows="3" cols="5" class="required-entry input-text" title="Comment" id="message" name="message"></textarea></td>
	</tr>

      </tbody>
     </table>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <input type="text" style="display:none !important;" value="" id="hideit" name="hideit">
        <button class="button submit-cancel-request" id="cancelform_submit" title="Submit"><span><span>Submit</span></span></button>
    </div>
</form>
<div class="response"></div>
    </div>
</div>

<style>
.bargainprice-adminhtml-bargainprice-cancel .header{ display:none;}
.bargainprice-adminhtml-bargainprice-cancel .demo-notice{ display:none;}
.bargainprice-adminhtml-bargainprice-cancel .notification-global{ display:none;} 
</style>

<script type="text/javascript">
	function closePopup() {
        Windows.close('browser_window');
    	}

$.noConflict();
jQuery(document).ready(function(){ 
jQuery('#cancelform_submit').live('click',function(){ 


	var minPrice= jQuery("#minimum_price").val();
	var msg = jQuery("#message").val();
	
	if(minPrice =='' || msg ==''){
		if( minPrice =='' && msg !=''){

					jQuery("#minimum_price").addClass("required-fail");
					jQuery("#message").removeClass("required-fail");

		}
		else if ( minPrice !='' && msg =='') {

					jQuery("#minimum_price").removeClass("required-fail");
					jQuery("#message").addClass("required-fail");
					

		}
		else if (minPrice =='' && msg ==''){
		
					jQuery("#minimum_price").addClass("required-fail");
					jQuery("#message").addClass("required-fail");
	
		}
	
		}

	else{
	
	var minimum_price = jQuery('#minimum_price').val();
	var new_message = jQuery('#message').val();
	var datastring = "minimum_price="+minimum_price+"&message="+new_message;
	var req_url = '<?php echo $req_url ; ?>';
	jQuery.ajax({
			type	: "GET",
			cache	: false,
			url	: req_url,
			data	: datastring,
			success: function(result_sub) {
			
				window.parent.location.reload();
				window.parent.closePopup();			
			}
		}); 
}
return false;


});
});
</script>